config/routes.rb
Rails.application.routes.draw do

  resources :budget_entries
  resources :budget_categories
  resources :categories
  resources :users do
    resources :budgets
  end

  get 'about'      => 'static_pages#about'
  get 'opensource' => 'static_pages#opensource'
  get 'signup'     => 'users#new'
  
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  root 'static_pages#home'
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  has_many :budget_categories
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = @user.budgets 
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = @user.budgets.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to user_budget_path(id: @budget), notice: 'budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to user_budget_path(id: @budget), notice: 'budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to user_budgets_url, notice: 'budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:user_id, :year, :month, :notes)
    end

    def set_user
      @user = User.find(params[:user_id])
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_for([user, budget]) do |f| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <div class="field">
    <%= f.label :month %>
    <%= f.text_field :month %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form', {budget: @budget, user: @user} %>

<%= link_to 'Show', user_budget_path %> |
<%= link_to 'Back', user_budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budgets</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Month</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= budget.year %></td>
        <td><%= budget.month %></td>
        <td><%= budget.notes %></td>
        <td><%= link_to 'Show', user_budget_path(id: budget) %></td>
        <td><%= link_to 'Edit', edit_user_budget_path(id: budget) %></td>
        <td><%= link_to 'Destroy', user_budget_path(id: budget), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget', new_user_budget_path %>

app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%= render 'form', {budget: @budget, user: @user} %>

<%= link_to 'Back', user_budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @budget.user_id %>
</p>

<p>
  <strong>Year:</strong>
  <%= @budget.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @budget.month %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @budget.notes %>
</p>

<%= link_to 'Edit', edit_user_budget_path(id: @budget) %> |
<%= link_to 'Back', user_budgets_path %>