config/routes.rb
Rails.application.routes.draw do

  resources :budget_entries
  resources :budget_categories
  resources :categories
  resources :users do
    resources :budgets
  end

  get 'about'      => 'static_pages#about'
  get 'opensource' => 'static_pages#opensource'
  get 'signup'     => 'users#new'
  
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  root 'static_pages#home'
end

app/models/budget_entry.rb
class BudgetEntry < ApplicationRecord
  belongs_to :budget_category
end

app/controllers/budget_entries_controller.rb
class BudgetEntriesController < ApplicationController
  before_action :set_budget_entry, only: [:show, :edit, :update, :destroy]

  # GET /budget_entries
  # GET /budget_entries.json
  def index
    @budget_entries = BudgetEntry.all
  end

  # GET /budget_entries/1
  # GET /budget_entries/1.json
  def show
  end

  # GET /budget_entries/new
  def new
    @budget_entry = BudgetEntry.new
  end

  # GET /budget_entries/1/edit
  def edit
  end

  # POST /budget_entries
  # POST /budget_entries.json
  def create
    @budget_entry = BudgetEntry.new(budget_entry_params)

    respond_to do |format|
      if @budget_entry.save
        format.html { redirect_to @budget_entry, notice: 'Budget entry was successfully created.' }
        format.json { render :show, status: :created, location: @budget_entry }
      else
        format.html { render :new }
        format.json { render json: @budget_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budget_entries/1
  # PATCH/PUT /budget_entries/1.json
  def update
    respond_to do |format|
      if @budget_entry.update(budget_entry_params)
        format.html { redirect_to @budget_entry, notice: 'Budget entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget_entry }
      else
        format.html { render :edit }
        format.json { render json: @budget_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budget_entries/1
  # DELETE /budget_entries/1.json
  def destroy
    @budget_entry.destroy
    respond_to do |format|
      format.html { redirect_to budget_entries_url, notice: 'Budget entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget_entry
      @budget_entry = BudgetEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_entry_params
      params.require(:budget_entry).permit(:budget_category_id, :amount, :notes)
    end
end

app/helpers/budget_entries_helper.rb
module BudgetEntriesHelper
end

app/views/budget_entries/_form.html.erb
<%= form_for(budget_entry) do |f| %>
  <% if budget_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget_entry.errors.count, "error") %> prohibited this budget_entry from being saved:</h2>

      <ul>
      <% budget_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :budget_category_id %>
    <%= f.number_field :budget_category_id %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budget_entries/edit.html.erb
<h1>Editing Budget Entry</h1>

<%= render 'form', budget_entry: @budget_entry %>

<%= link_to 'Show', @budget_entry %> |
<%= link_to 'Back', budget_entries_path %>

app/views/budget_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budget Entries</h1>

<table>
  <thead>
    <tr>
      <th>Budget category</th>
      <th>Amount</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budget_entries.each do |budget_entry| %>
      <tr>
        <td><%= budget_entry.budget_category_id %></td>
        <td><%= budget_entry.amount %></td>
        <td><%= budget_entry.notes %></td>
        <td><%= link_to 'Show', budget_entry %></td>
        <td><%= link_to 'Edit', edit_budget_entry_path(budget_entry) %></td>
        <td><%= link_to 'Destroy', budget_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget Entry', new_budget_entry_path %>

app/views/budget_entries/new.html.erb
<h1>New Budget Entry</h1>

<%= render 'form', budget_entry: @budget_entry %>

<%= link_to 'Back', budget_entries_path %>

app/views/budget_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Budget category:</strong>
  <%= @budget_entry.budget_category_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @budget_entry.amount %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @budget_entry.notes %>
</p>

<%= link_to 'Edit', edit_budget_entry_path(@budget_entry) %> |
<%= link_to 'Back', budget_entries_path %>